spring:
  application:
    name: eureka-client
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:alunodb

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
