server:
  port: ${PORT:8088}

management:
  endpoints:
    web:
      exposure:
        include: refresh
    health:
      show-details: always
  
spring:
  application:
    name: discipline-services
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:alunodb

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

---
spring:
  profiles: other

server:
  port: ${PORT:18088}